### PR TITLE
Version 3.6.3

### PR DESCRIPTION
**Pull request by sambulance**
This is the initial beta release. Download here: 
[BackUpWordPress-3.6.3-beta.zip](https://github.com/humanmade/backupwordpress/files/617058/BackUpWordPress-3.6.3-beta.zip)

I've tested locally and on my rubbish £3/month shared hosting, all working well for me.

Todo:

- [x] Confirm beta version works as expected (@katmoody to send beta plugin to testers)
- [x] Change version number to 3.6.3
- [x] Run `grunt release`
- [x] Commit new version to this branch
- [ ] Merge this branch

_From [wiki](https://github.com/humanmade/backupwordpress/wiki/Releasing-to-wp.org):_
- [ ] Tag the release: `git tag -a x.x.x -m "version x.x.x"`, `git push --tags`
- [ ] Create a tag folder in `svn/tags` for the new version
- [ ] svn commit the tag folder and the trunk folder

@pdewouters/@willmot As I've not done this before, I'd appreciate a once over please.

### CODE REVIEW

**Comment by katmoody** [comment]
Thanks @sambulance - I've sent the beta out to perhaps 10 users and will report back with their results. I'll also be updating issues in the WP forums that might be similar to see if any of those folks want to test it as well.

**Comment by pdewouters** [comment]
@sambulance that's pretty impressive that you managed to do the new version! it's quite a convoluted process at the moment, so well done. there's a ticket about improving the release process somewhere.

**Comment by sambulance** [comment]
Thanks @pdewouters, I just followed your docs 🙂

**Comment by sambulance** [comment]
New beta: 
[BackUpWordPress-3.6.3.1-beta.zip](https://github.com/humanmade/backupwordpress/files/643234/BackUpWordPress-3.6.3.1-beta.zip)

**Comment by katmoody** [comment]
@sambulance I listed this for a couple folks in Intercom to check out but I'm unsure if there will be a real answer since both had already renewed their licenses ;-)

**Comment by kat** [comment]
hey @sambulance can you change kat to katmoody in the checklist at the top :-) thx

**Pull request merged**
