### PR TITLE
[WIP] Adds PHP mysqldump fallback lib

### PR DESCRIPTION
**Pull request by pdewouters**
Now points to `dev-master` to get latest commits

### CODE REVIEW

**Comment by willmot** [comment]
This is a large change to a really important part of complex, core functionality, we need to be confident that merging this will:

1. ~~Works~~ Unit tests pass which is a solid indication that it does.
2. Improves our PHP fallback database backups
3. Cause as few unintended breakages as possible

@pdewouters how much testing etc. has gone into this so far? What else do you think we need to do before we decide to merge and release?

**Comment by pdewouters** [comment]
At present, I ran a DB only backup and tested the import.

**Comment by willmot** [comment]
Couple of quick thoughts

- [ ] I notice it requires PDO, from some quick Googling it seems PDO is a default extension from PHP 5.1+, is having PDO as a dependancy going to be an issue?
- [ ] Given this class aims to mirror `mysqldump` we should make an effort to use the same settings for it as we use for `mysqldump`.

I'm a pretty big +1 on this, I think it will give us a much more robust PHP mysqldump implementation with a lot more consistency between it and the real `mysqldump`, it should also fix a bunch of bugs (both known and unknown) with our current implementation.

But we should do more testing first.

**Comment by pdewouters** [comment]
> is having PDO as a dependancy going to be an issue
Would you rather leave the current function in for servers that don't support PDO?

**Comment by willmot** [comment]
I guess first thing is we should try to work out whether PDO is ever not available, if it's always there then no need for a fallback, I'd strongly prefer not to have to leave the current implementation in as well.

**Comment by willmot** [comment]
- [ ] Another thought, do we need to specifically pass in `DB_CHARSET` to support databases that don't use the default (`utf8`)

**Comment by pdewouters** [comment]
looks like you can pass quite a few params https://github.com/ifsnop/mysqldump-php#dump-settings

**Comment by pdewouters** [comment]
author has tagged a new release https://github.com/ifsnop/mysqldump-php/releases/tag/v1.6

**Comment by willmot** [comment]
Let's talk through our merge plan for this in our Friday dev chat, I want to be sure we've covered our bases so that we don't cause a spike in support issues post release.

**Comment by willmot** [comment]
@markoheijnen I know you've done a bunch of looking into PDO etc. Is it safe to assume all PHP 5.1 > installs have PDO support? Or should we be providing a fallback for people that don't?

**Comment by willmot** [comment]
In terms of moving towards merge, the open questions are

**Do we need to provide a fallback if `PDO_MYSQL` isn't enabled?**
 - [ ]@pdewouters to test on some common hosts
 - [ ] Start tracking PDO support in Intercom https://github.com/humanmade/backupwordpress/issues/848
 - [ ] Reach out to @markoheijnen

**Comment by markoheijnen** [comment]
There are some changes made in PHP in the beginning and I believe the PDO library could be disabled in 5.1 unsure about 5.2. I do know that people had issues with it but I never experienced that. What people do say is that since PHP 5.3 and later should be more then fine.

Note that I played with it on a lower scale then this plugin will do.

**Comment by willmot** [comment]
Cools cheers @markoheijnen, we require 5.3 so I think we'll be fine.

**Comment by pdewouters** [comment]
bedankt ;)

**Comment by pdewouters** [comment]
Developers can change the dump options by filtering `hmbkp_mysqldump_fallback_dump_settings`, for example if you wanted to switch the `single-transaction` flag to false:
````
add_filter( 'hmbkp_mysqldump_fallback_dump_settings', function( $options ) {
  return array_merge(
    $options,
    array( 'single-transaction' => true ),
  )
});
````

**Comment by willmot** [comment]
Nice, do you think we need to separate filters for `mysqldump` and `mysqldump_fallback` or can they just use the same settings now?

**Comment by pdewouters** [comment]
We could probably abstract out the configuration into its own function and use it in both cases, yes

**Comment by pdewouters** [comment]
So, for socket connections, we'll still need to parse the `DB_HOST` value and just construct a DSN string from it to pass as a parameter to the constructor. Not sure when this will be implemented though.
I guess we'll have to set this on hold?

**Comment by ifsnop** [comment]
Hi there,

In the new version of mysqldump-php (take a look at the devel branch), ia now possible to connect using sockets, using the standard dsn string.

Here is the function that parses the dsn string and extracts dbname, host, socket, etc:

https://github.com/ifsnop/mysqldump-php/blob/devel/src/Ifsnop/Mysqldump/Mysqldump.php#L213

Hope that it helps.

**Comment by pdewouters** [comment]
cheers @ifsnop , really appreciate that you added the feature so fast :+1: 
We have our weekly dev chat later and will discuss how to best test it.

**Comment by ifsnop** [comment]
Think in using mysqldump-php not only as a fallback, but as a complete
solution, and forget calling the mysqldump binary.   You will get a php
only solution,  easier to maintain.

**Comment by willmot** [comment]
I've been wondering the same, my only concern would be performance, especially when dumping large DB's (say > 1GB), have you done any benchmarking to measure performance?

**Comment by pdewouters** [comment]
yeah , I was thinking exactly the same!

**Comment by ifsnop** [comment]
Could anyone provide a testing dataset so we could all share benchmarcks?

I've been wondering the same, my only concern would be performance,
especially when dumping large DB's (say > 1GB), have you done any
benchmarking to measure performance?

—
Reply to this email directly or view it on GitHub
<https://github.com/humanmade/backupwordpress/pull/835#issuecomment-126638661>
.

**Comment by pdewouters** [comment]
https://github.com/humanmade/backupwordpress/issues/856

**Comment by ifsnop** [comment]
I did some  testing:
~~~
CREATE TABLE `test000` (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `guid` varchar(36) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  `text` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
~~~
Filled with some random values:
~~~
+------------+--------+------------+------------+----------------+---------------+---------------+------------+
| table_name | engine | row_format | table_rows | avg_row_length | total_mb      | data_mb       | index_mb   |
+------------+--------+------------+------------+----------------+---------------+---------------+------------+
| test000    | InnoDB | Compact    |     336192 |           5046 | 1618.00000000 | 1618.00000000 | 0.00000000 |
+------------+--------+------------+------------+----------------+---------------+---------------+------------+
~~~
Small example:

~~~
INSERT INTO `test000` VALUES (1,'6608D7AC-E472-AB1C-3A4C-8F173B8ADCA2','Leigh','in.hendrerit.consectetuer@diamatpretium.org','New
South Wales','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Eti am vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nul.... 
~~~

Results:
~~~
# time mysqldump test003 > mysqldump_test003.sql
real    0m13.578s
user    0m10.236s
sys     0m1.388s

# time php test.php
real    0m32.219s
user    0m22.788s
sys     0m4.104s
~~~

Please do you own tests!

**Comment by pdewouters** [comment]
Another argument for this is that the current function uses `mysql_` function instead of `mysqli_` or PDO functions.

**Comment by pdewouters** [comment]
I can't get my hands on a really large database for testing this, any suggestions?

**Comment by willmot** [comment]
We're going to merge this, @pdewouters just doing final work to support Socket connections and then it's going in \0/

**Comment by pdewouters** [comment]
@willmot updated the library to `2.0` , it now requires a PDO connection string. 
I tested a socket connection locally, `define('DB_HOST', 'localhost:/var/run/mysqld/mysqld.sock');`
you can easily find the path to the socket in the phpinfo output

**Comment by willmot** [comment]
@pdewouters great, ready to ship?

**Comment by pdewouters** [comment]
@willmot can you remind me about this?

> Make sure we are passing in the same args as we pass to mysqldump.

**Comment by ifsnop** [comment]
Recently a bug was discovered, and databases with uppercase letters weren't
parsed. No release was made, but it has already been commited to master.

In a few hours I'll make a release, adding some new dump options.

Regards,

On Thu, Oct 22, 2015 at 12:48 PM, Paul de Wouters <notifications@github.com>
wrote:

> @willmot <https://github.com/willmot> can you remind me about this?
>
> Make sure we are passing in the same args as we pass to mysqldump.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humanmade/backupwordpress/pull/835#issuecomment-150177953>
> .
>



-- 
-- Use of a keyboard or mouse may be linked to serious injuries or
disorders.
diego dot torres at gmail dot com - Madrid / Spain

**Comment by willmot** [comment]
@pdewouters as we're using both `mysqldump` via cli and `php-mysqldump` as a fallback we should make sure we have them both congfigured the same with the same options passed etc.

**Comment by pdewouters** [comment]
thanks @ifsnop for the update

**Comment by willmot** [comment]
All tests pass, merge train is leaving the station

🚄 choo choo

**Comment by pdewouters** [comment]
@ifsnop did you ever release an update for the bugfix you mention?

**Comment by ifsnop** [comment]
Yes, it was done a few hours after my post, you can see it here https://github.com/ifsnop/mysqldump-php/releases/tag/v2.1

**Comment by pdewouters** [comment]
thanks!

**Pull request merged**
