### PR TITLE
Use Process for all our system calls

### PR DESCRIPTION
**Pull request by willmot**
- Replaces all usage of exec
- Removes helper functions and unit tests that dealt with whether exec was available
- Adds Process 2.x to composer
- Process relies on `proc_open` rather than `exec` under the hood so we check for that before using
- Simplifies the errors we bubble up from shell commands, we now only bubble errors when the command reports it failed rather than also bubbling warnings from successful runs.
- Fixes a bug in `verify_backup` that meant we weren't correctly falling back in instances where the process reported an error but the backup file (database or zip) was created (even only partially). Adds unit tests for this.

### CODE REVIEW

**Comment by willmot** [comment]
> Simplifies the errors we bubble up from shell commands, we now only bubble errors when the command reports it failed rather than also bubbling warnings from successful runs.

This is will reduce the amount the of useless errors we show people (see https://github.com/humanmade/backupwordpress/issues/970).

**Comment by willmot** [comment]
I'm also interested to see whether this helps with https://github.com/humanmade/backupwordpress/issues/979

@katmoody do we have anyone who's running into the incomplete database issue that could test a beta here?

**Comment by willmot** [comment]
We should consider using `ProcessBuilder` to build our more complex commands: http://symfony.com/doc/current/components/process.html#executing-php-code-in-isolation

**Comment by willmot** [comment]
@pdewouters I think I'm done with this. Would appreciate you testing locally and giving a thorough review/merge.

@katmoody we'll want to beta test this change with a few people who are running into issues. 

I specifically think it will resolve https://github.com/humanmade/backupwordpress/issues/979 & https://github.com/humanmade/backupwordpress/issues/986

**Comment by pdewouters** [comment]
tested on @katmoody 's test site which uses `ZipArchive` and this doesn't conflict and tested locally on an install that has the zip command and backups work ok (db and complete)

**Comment by willmot** [comment]
@pdewouters great! I'm happy to go for merge in that case. We can open a separate issue to cover implementing `ProcessBuilder`.

Once we have everything merged into master we can do a 3.5 beta and see if @katmoody can test with some of the folks who're running into the issues this intends to fix.

**Comment by pdewouters** [comment]
@willmot sorry, deleted previous message, as I realized I hadn't ran composer install ,so was missing the Process library

**Comment by willmot** [comment]
Huh, wouldn't that have caused a fatal?

**Comment by pdewouters** [comment]
```
[29-Feb-2016 11:55:20 UTC] PHP Fatal error:  Uncaught exception 'Symfony\Component\Process\Exception\ProcessTimedOutException' with message 'The process "cd '/srv/www/wordpress-default' && zip -rq '/srv/www/wordpress-default/wp-content/backupwordpress-cbaa44a22d-backups/local-wordpress-dev-1445593823-complete-2016-02-29-11-54-16.zip' ./ -x '*.svn*' -x '*_svn*' -x '*CVS*' -x '*_darcs*' -x '*.arch-params*' -x '*.monotone*' -x '*.bzr*' -x '*.git*' -x '*.hg*' -x '*backwpup-**' -x '*updraft*' -x '*wp-snapshots*' -x '*backupbuddy_backups*' -x '*pb_backupbuddy*' -x '*backup-db*' -x '*Envato-backups*' -x '*managewp*' -x '*backupwordpress-*-backups*' -x '*wp-content/backupwordpress-cbaa44a22d-backups*'" exceeded the timeout of 60 seconds.' in /srv/www/wordpress-default/wp-content/plugins/backupwordpress/vendor/symfony/process/Process.php:1192
Stack trace:
#0 /srv/www/wordpress-default/wp-content/plugins/backupwordpress/vendor/symfony/process/Process.php(364): Symfony\Component\Process\Process->checkTimeout()
#1 /srv/www/wordpress-default/wp-content/plugins/backu in /srv/www/wordpress-default/wp-content/plugins/backupwordpress/vendor/symfony/process/Process.php on line 1192
```

**Comment by willmot** [comment]
@pdewouters made some additional minor improvements:

- No need to increase the timeout for the `mysql --execute=quit` command as that should be quick. If for some reason the cli database connection does take 60 seconds to connect we probably do want to treat that as an error and fallback to PHP anyway.
- Catches `\Exception` instead of `ProcessTimedOutException` in `Zip_File_Backup_Engine` which brings it into line with `Mysqldump_Database_Backup_Engine`.
- Avoids a possible warning in the `test_file_with_strange_characters` unit test by ensuring that the backup file actually exists before attempting to access it's contents.

FYI, for testing purposes you can change the timeout to something like `0.001` to force a timeout Exception.

**Comment by willmot** [comment]
@pdewouters looks like https://github.com/humanmade/backupwordpress/commit/3adf43457cf65becdcad545f3ecc446caacaac13#diff-58e989755f27612a26203553671d2897 was a bad merge, getting a fatal error when trying to load the plugin admin page:

```
Fatal error: Call to undefined method HM\BackUpWordPress\Backup_Utilities::is_exec_available()
```

That was fixed in https://github.com/humanmade/backupwordpress/commit/f33cb44da3e62db90db80f914045dd0766249f1f but looks like it was undone.

Re-fixed in 695c46b

**Comment by willmot** [comment]
- [ ] I need to test this on Windows.

**Comment by pdewouters** [comment]
yeah I did a bad merge, then fixed it. sorry if it caused you an issue

**Comment by willmot** [comment]
> yeah I did a bad merge, then fixed it. sorry if it caused you an issue

No worries, was just noting 👍

**Comment by willmot** [comment]
Unit tests run without issue on Windows, I also manually ran through and smoke tested creating backups etc. I think this is ready for merge 👍

**Pull request merged**
