### PR TITLE
Move closing div tag

### PR DESCRIPTION
**Pull request by pdewouters**
The schedule sentence div was containing the schedule settings form, instead of them being on the same level

### CODE REVIEW

**Comment by willmot** [comment]
@pdewouters to post a screenshot so it's clear this doesn't break things visually.

**Comment by pdewouters** [comment]
1. Schedule settings at same level as Schedule sentence

screen shot 2015-01-26 at 10 41 15
screen shot 2015-01-26 at 10 40 13

2. Schedule settings in the Schedule sentence div

screen shot 2015-01-26 at 10 43 17
screen shot 2015-01-26 at 10 42 33

IMO , semantically, they should be at the same level. Thoughts? Maybe you wanted them to be in the same "box" with left/right padding?

**Comment by willmot** [comment]
hmm, not sure I agree.

The settings are semantically under the link to edit those settings, I think it ties them together nicely.

**Comment by pdewouters** [comment]
ah, you're right - I see that now.

**Pull request closed without merging**
