### PR TITLE
README: Add information about constants

### PR DESCRIPTION
**Pull request by siruguri**
* Specifically, note that HMBKP_SCHEDULE_TIME overrides browser-entered
  time settings for a schedule.

### CODE REVIEW

**Comment by pdewouters** [comment]
@siruguri thanks for the pull request! We have detailed information about setting the constants in the help tab on the admin page BTW

**Comment by siruguri** [comment]
Cool! The admin page tab doesn't explain that the constants are the final say - somehow, I feel that browser-entered data should be the last word, esp from the pov of "non techie" users. Even I had to actually read the code to confirm that in fact the `wp-config` constants were being read over the settings. Thought it might be helpful to make it explicit in the README.

**Comment by pdewouters** [comment]
Good point. We should probably make it clearer to users how the contants work.
@owaincuvelier could we add a section to the support center explaining this? We could then copy it to the readme file.

**Comment by owaincuvelier** [comment]
Yeah good idea.

**Comment by pdewouters** [comment]
Awesome. Closing this as we have actually generate the readme file from a script.

**Pull request closed without merging**
