### PR TITLE
Exclude Envato-backups folders by default

### PR DESCRIPTION
**Pull request by pdewouters**
***Original issue***
There's also a managewp folder we can exclude. Additionally, I don't know what plugin it originated from but I saw a ```backups-*****``` folder, maybe we can catch that too.

***PR Summary***
I took a bit of a deep dive into how we were calculating directory sizes and scanning the filesystem.
I tried to consolidate our different scanning functions to use the Symfony Finder component which provides a layer of abstraction on top of the SPL Iterators.
It will allow us to do more complex "queries" in the future. It also irons out a few bugs in the default PHP Iterators and deals with cross platform inconsistencies. It's compatible with PHP 5.3

Whenever you see a directory size now, it has been calculated without the default excluded folders, for example any `.git` folder will not be taken into account for calculating the size of the folder.

### CODE REVIEW

**Comment by pdewouters** [comment]
- [ ] change to default rules

screen shot 2015-02-28 at 18 12 56

**Comment by pdewouters** [comment]
- [] Fix dir sizes

**Comment by pdewouters** [comment]
So we have different sizes we could display for site and directories:

- For site: total size / total size minus excludes
- For each dir: total size / total size minus excludes

**Comment by willmot** [comment]
> change to default rules

Can we only show those rules if those directories actually exist, otherwise might be confusing to users who have no idea what those are.

> We can show them both, e.g. (T:642MB | E:432MB) or add a Javascript toggle button

How about we just show the total amount size not counting excludes but then in a tooltip we show both with clear labelling.

`643MB in total but 352MB is excluded so only 291MB will be included in your backup`

Same for site size

`2.3GB in total but 1.8GB is excluded so only 535MB will be included in your backup`

Thoughts?

**Comment by pdewouters** [comment]
screen shot 2015-03-03 at 15 32 22

As we don't actually scan to see if they exist and they are wildcard patterns, I just hid them.
I think this is good enough for this PR.
I'd rather focus on other issues, we can always come back and fine tune this later

**Comment by willmot** [comment]
Great idea!

**Comment by pdewouters** [comment]
\0/ :shipit:

**Pull request merged**
