### PR TITLE
Admin performance improvements

### PR DESCRIPTION
**Pull request by willmot**
Some attempts to reduce the impact BackUpWordPress has on admin performance.

### CODE REVIEW

**Comment by willmot** [comment]
@dashaluna @pdewouters could one of you review/merge and then we can release.

**Comment by pdewouters** [comment]
@willmot did you do any benchmarks?

**Comment by willmot** [comment]
Yep, locally for me this cut general page load performance in half and dropped the backups page itself about 8x.

I used query monitor to track which queries were getting called on those pages and then just transient cached around each of them.

**Comment by pdewouters** [comment]
@willmot `set_transient` 3d argument should be `Time until expiration in seconds from now`, not a unix timestamp

**Comment by willmot** [comment]
Ah good catch 👍

**Comment by dashaluna** [comment]
@willmot all fixed, I haven't run unit tests, as I'm still working on setting it up. Do you want to give it a run on unit tests and merge if they are ok?

**Pull request merged**
