### PR TITLE
Prevent cron interval dupes

### PR DESCRIPTION
**Pull request by pdewouters**

### CODE REVIEW

**Comment by willmot** [comment]
@pdewouters this ready for merge?

**Comment by pdewouters** [comment]
yes

**Comment by willmot** [comment]
Needs master merging

**Comment by willmot** [comment]
@pdewouters I'm bumping plugin version to 3.3 Alpha in https://github.com/humanmade/backupwordpress/commit/5917db1e38a145fec984a92ae3f03ccc3490d2c6 as it's needed for upgrade routine to run. 

Happy for this to be merged if you agree with that.

**Pull request merged**
