### PR TITLE
1105 default excludes

### PR DESCRIPTION
**Pull request by dashaluna**
Issue #1105

### CODE REVIEW

**Comment by dashaluna** [comment]
@willmot not sure why travis failed. How do I restart the tests?

**Comment by willmot** [comment]
For some reason it's trying to test against a non-existent branch. It should be testing against this branch `1105-default-excludes` but instead it's trying to test against `1105-default-excludes-rules`. Do you recognise that branch name? Regardless, [this branch passes](https://travis-ci.org/humanmade/backupwordpress/builds/162250186) so we can safely merge.

**Comment by dashaluna** [comment]
@willmot sorry, something went wrong with my commits, so I deleted the branch and pushed again, with different name. So probably it got messed up in there too. Apologies.

**Comment by dashaluna** [comment]
@willmot also, I've noticed that when PRs are merged the linked issues aren't closed automatically. I think it was doing it before or have I imagined it?

**Comment by willmot** [comment]
No worries!

Linked issues will only auto close if the PR description or one of the commit messages includes fixes or closes #issue-number

**Comment by dashaluna** [comment]
So instead of this PRs description as `Issue #1105` I can say `Fixes Issue #1105`?

**Comment by willmot** [comment]
yep

**Pull request merged**
