### PR TITLE
Updated and extended German translation.

### PR DESCRIPTION
**Pull request by herrherrmann**
^_^

### CODE REVIEW

**Comment by herrherrmann** [comment]
I just noticed you don't want direct pull requests for language updates. I've sent you an email.

**Comment by willmot** [comment]
@herrherrmann thanks for the contribution, @pdewouters given the issues with translate.hmn.md maybe we should just take PR's?

**Comment by herrherrmann** [comment]
Oh ok, in this case I'll just reopen this one…

**Comment by pdewouters** [comment]
yep! that's fine thanks

**Pull request merged**
